<script setup>
import { computed, onMounted, ref } from 'vue';
import { createUser, listRoles, listUsers, saveUser } from '../api/trace.js';
import { showAlert } from '../ui-feedback.js';
const roles = ref({}), users = ref({}), username = ref(''), password = ref(''), createRole = ref(''), choices = ref({});
const entries = computed(() => Object.entries(users.value));
async function loadRoles() { const config = await listRoles(); roles.value = config.roles || {}; if (!createRole.value) createRole.value = Object.keys(roles.value)[0] || ''; }
async function loadUsers() { const config = await listUsers(); users.value = config.users || {}; choices.value = Object.fromEntries(Object.entries(users.value).map(([name, user]) => [name, user.role])); }
async function load() { try { await loadRoles(); await loadUsers(); } catch (error) { showAlert(error.message); } }
async function create() { try { const config = await createUser({ username: username.value.trim(), password: password.value, role: createRole.value }); users.value = config.users || {}; username.value = ''; password.value = ''; choices.value = Object.fromEntries(Object.entries(users.value).map(([name, user]) => [name, user.role])); } catch (error) { showAlert(error.message); } }
async function save(name) { try { const config = await saveUser(name, choices.value[name]); users.value = config.users || {}; choices.value = Object.fromEntries(Object.entries(users.value).map(([key, user]) => [key, user.role])); } catch (error) { showAlert(error.message); } }
onMounted(load);
</script>
<template><section class="page-content"><div class="card" style="margin-bottom:24px"><div class="section-title">用户管理</div><div class="user-create-row"><div class="field-group" style="margin-bottom:0"><label>用户名</label><input v-model="username" class="field-input" placeholder="例如 BX100"></div><div class="field-group" style="margin-bottom:0"><label>密码</label><input v-model="password" class="field-input" type="password" placeholder="输入密码"></div><div class="field-group" style="margin-bottom:0"><label>角色</label><select v-model="createRole" class="field-select"><option v-for="(role, key) in roles" :key="key" :value="key">{{ role.label || key }}</option></select></div><button class="btn-primary" @click="create"><i class="ti ti-user-plus"></i> 创建用户</button></div><div class="user-grid"><div v-for="[name, user] in entries" :key="name" class="user-card"><div><div class="user-name">{{ name }}</div><div class="role-key">当前角色：{{ roles[user.role]?.label || user.role }}</div></div><div class="user-actions"><select v-model="choices[name]" class="field-select"><option v-for="(role, key) in roles" :key="key" :value="key">{{ role.label || key }}</option></select><button class="btn-outline role-save-btn" @click="save(name)"><i class="ti ti-device-floppy"></i> 保存</button></div></div></div></div></section></template>
